name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install -y android-sdk

      - name: Accept Android Licenses
        run: |
          yes | sudo sdkmanager --licenses

      - name: Install Android Build Tools (AIDL fix)
        run: |
          sudo sdkmanager "platform-tools"
          sudo sdkmanager "platforms;android-33"
          sudo sdkmanager "build-tools;33.0.2"

      - name: Install Python Tools
        run: |
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
